# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rccar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import motor_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='rccar.proto',
  package='',
  serialized_pb=_b('\n\x0brccar.proto\x1a\x0bmotor.proto\">\n\x0b\x43\x61rSteerMsg\x12\r\n\x05speed\x18\x01 \x02(\x11\x12\r\n\x05right\x18\x02 \x02(\x02\x12\x11\n\tcam_right\x18\x03 \x02(\x02\".\n\x07PingMsg\x12\x0f\n\x07seq_num\x18\x01 \x02(\r\x12\x12\n\ntime_stamp\x18\x02 \x02(\r\"\xb9\x01\n\x0c\x43\x61rStatusMsg\x12\r\n\x05speed\x18\x01 \x02(\x02\x12\x15\n\rphase_current\x18\x02 \x02(\x02\x12\x0f\n\x07voltage\x18\x03 \x02(\x02\x12\x15\n\rpwm_magnitude\x18\x04 \x02(\x02\x12\x13\n\x0btemperature\x18\x05 \x02(\x02\x12\x0f\n\x07\x65uler_h\x18\x06 \x02(\x02\x12\x0f\n\x07\x65uler_p\x18\x07 \x02(\x02\x12\x0f\n\x07\x65uler_b\x18\x08 \x02(\x02\x12\x13\n\x0bsystem_load\x18\t \x02(\x02\"\\\n\x16\x43\x61rControlContainerMsg\x12\x1d\n\x05steer\x18\x01 \x01(\x0b\x32\x0c.CarSteerMsgH\x00\x12\x18\n\x04ping\x18\x02 \x01(\x0b\x32\x08.PingMsgH\x00\x42\t\n\x07payload\"\x95\x01\n\x15\x43\x61rReportContainerMsg\x12\x1f\n\x06status\x18\x01 \x01(\x0b\x32\r.CarStatusMsgH\x00\x12-\n\x13scope_phase_current\x18\x02 \x01(\x0b\x32\x0e.MotorScopeMsgH\x00\x12!\n\rping_response\x18\x03 \x01(\x0b\x32\x08.PingMsgH\x00\x42\t\n\x07payload')
  ,
  dependencies=[motor_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CARSTEERMSG = _descriptor.Descriptor(
  name='CarSteerMsg',
  full_name='CarSteerMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='CarSteerMsg.speed', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='right', full_name='CarSteerMsg.right', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cam_right', full_name='CarSteerMsg.cam_right', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=90,
)


_PINGMSG = _descriptor.Descriptor(
  name='PingMsg',
  full_name='PingMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seq_num', full_name='PingMsg.seq_num', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='time_stamp', full_name='PingMsg.time_stamp', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=138,
)


_CARSTATUSMSG = _descriptor.Descriptor(
  name='CarStatusMsg',
  full_name='CarStatusMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='CarStatusMsg.speed', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase_current', full_name='CarStatusMsg.phase_current', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='CarStatusMsg.voltage', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pwm_magnitude', full_name='CarStatusMsg.pwm_magnitude', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='CarStatusMsg.temperature', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='euler_h', full_name='CarStatusMsg.euler_h', index=5,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='euler_p', full_name='CarStatusMsg.euler_p', index=6,
      number=7, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='euler_b', full_name='CarStatusMsg.euler_b', index=7,
      number=8, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='system_load', full_name='CarStatusMsg.system_load', index=8,
      number=9, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=326,
)


_CARCONTROLCONTAINERMSG = _descriptor.Descriptor(
  name='CarControlContainerMsg',
  full_name='CarControlContainerMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steer', full_name='CarControlContainerMsg.steer', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ping', full_name='CarControlContainerMsg.ping', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='CarControlContainerMsg.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=328,
  serialized_end=420,
)


_CARREPORTCONTAINERMSG = _descriptor.Descriptor(
  name='CarReportContainerMsg',
  full_name='CarReportContainerMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='CarReportContainerMsg.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scope_phase_current', full_name='CarReportContainerMsg.scope_phase_current', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ping_response', full_name='CarReportContainerMsg.ping_response', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='CarReportContainerMsg.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=423,
  serialized_end=572,
)

_CARCONTROLCONTAINERMSG.fields_by_name['steer'].message_type = _CARSTEERMSG
_CARCONTROLCONTAINERMSG.fields_by_name['ping'].message_type = _PINGMSG
_CARCONTROLCONTAINERMSG.oneofs_by_name['payload'].fields.append(
  _CARCONTROLCONTAINERMSG.fields_by_name['steer'])
_CARCONTROLCONTAINERMSG.fields_by_name['steer'].containing_oneof = _CARCONTROLCONTAINERMSG.oneofs_by_name['payload']
_CARCONTROLCONTAINERMSG.oneofs_by_name['payload'].fields.append(
  _CARCONTROLCONTAINERMSG.fields_by_name['ping'])
_CARCONTROLCONTAINERMSG.fields_by_name['ping'].containing_oneof = _CARCONTROLCONTAINERMSG.oneofs_by_name['payload']
_CARREPORTCONTAINERMSG.fields_by_name['status'].message_type = _CARSTATUSMSG
_CARREPORTCONTAINERMSG.fields_by_name['scope_phase_current'].message_type = motor_pb2._MOTORSCOPEMSG
_CARREPORTCONTAINERMSG.fields_by_name['ping_response'].message_type = _PINGMSG
_CARREPORTCONTAINERMSG.oneofs_by_name['payload'].fields.append(
  _CARREPORTCONTAINERMSG.fields_by_name['status'])
_CARREPORTCONTAINERMSG.fields_by_name['status'].containing_oneof = _CARREPORTCONTAINERMSG.oneofs_by_name['payload']
_CARREPORTCONTAINERMSG.oneofs_by_name['payload'].fields.append(
  _CARREPORTCONTAINERMSG.fields_by_name['scope_phase_current'])
_CARREPORTCONTAINERMSG.fields_by_name['scope_phase_current'].containing_oneof = _CARREPORTCONTAINERMSG.oneofs_by_name['payload']
_CARREPORTCONTAINERMSG.oneofs_by_name['payload'].fields.append(
  _CARREPORTCONTAINERMSG.fields_by_name['ping_response'])
_CARREPORTCONTAINERMSG.fields_by_name['ping_response'].containing_oneof = _CARREPORTCONTAINERMSG.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['CarSteerMsg'] = _CARSTEERMSG
DESCRIPTOR.message_types_by_name['PingMsg'] = _PINGMSG
DESCRIPTOR.message_types_by_name['CarStatusMsg'] = _CARSTATUSMSG
DESCRIPTOR.message_types_by_name['CarControlContainerMsg'] = _CARCONTROLCONTAINERMSG
DESCRIPTOR.message_types_by_name['CarReportContainerMsg'] = _CARREPORTCONTAINERMSG

CarSteerMsg = _reflection.GeneratedProtocolMessageType('CarSteerMsg', (_message.Message,), dict(
  DESCRIPTOR = _CARSTEERMSG,
  __module__ = 'rccar_pb2'
  # @@protoc_insertion_point(class_scope:CarSteerMsg)
  ))
_sym_db.RegisterMessage(CarSteerMsg)

PingMsg = _reflection.GeneratedProtocolMessageType('PingMsg', (_message.Message,), dict(
  DESCRIPTOR = _PINGMSG,
  __module__ = 'rccar_pb2'
  # @@protoc_insertion_point(class_scope:PingMsg)
  ))
_sym_db.RegisterMessage(PingMsg)

CarStatusMsg = _reflection.GeneratedProtocolMessageType('CarStatusMsg', (_message.Message,), dict(
  DESCRIPTOR = _CARSTATUSMSG,
  __module__ = 'rccar_pb2'
  # @@protoc_insertion_point(class_scope:CarStatusMsg)
  ))
_sym_db.RegisterMessage(CarStatusMsg)

CarControlContainerMsg = _reflection.GeneratedProtocolMessageType('CarControlContainerMsg', (_message.Message,), dict(
  DESCRIPTOR = _CARCONTROLCONTAINERMSG,
  __module__ = 'rccar_pb2'
  # @@protoc_insertion_point(class_scope:CarControlContainerMsg)
  ))
_sym_db.RegisterMessage(CarControlContainerMsg)

CarReportContainerMsg = _reflection.GeneratedProtocolMessageType('CarReportContainerMsg', (_message.Message,), dict(
  DESCRIPTOR = _CARREPORTCONTAINERMSG,
  __module__ = 'rccar_pb2'
  # @@protoc_insertion_point(class_scope:CarReportContainerMsg)
  ))
_sym_db.RegisterMessage(CarReportContainerMsg)


# @@protoc_insertion_point(module_scope)
