/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9.1 at Sat Oct  6 17:20:43 2018. */

#ifndef PB_MOTOR_PB_H_INCLUDED
#define PB_MOTOR_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _MotorControlMsg {
    int32_t speed;
/* @@protoc_insertion_point(struct:MotorControlMsg) */
} MotorControlMsg;

typedef struct _MotorScopeMsg {
    uint32_t period;
    pb_callback_t values;
/* @@protoc_insertion_point(struct:MotorScopeMsg) */
} MotorScopeMsg;

typedef struct _MotorStatusMsg {
    float speed;
    float phase_current;
    float voltage;
    float pwm_magnitude;
    float temperature;
/* @@protoc_insertion_point(struct:MotorStatusMsg) */
} MotorStatusMsg;

typedef struct _MotorReportContainerMsg {
    pb_size_t which_payload;
    union {
        MotorStatusMsg status;
        MotorScopeMsg scope_phase_current;
    } payload;
/* @@protoc_insertion_point(struct:MotorReportContainerMsg) */
} MotorReportContainerMsg;

/* Default values for struct fields */

/* Initializer values for message structs */
#define MotorControlMsg_init_default             {0}
#define MotorStatusMsg_init_default              {0, 0, 0, 0, 0}
#define MotorScopeMsg_init_default               {0, {{NULL}, NULL}}
#define MotorReportContainerMsg_init_default     {0, {MotorStatusMsg_init_default}}
#define MotorControlMsg_init_zero                {0}
#define MotorStatusMsg_init_zero                 {0, 0, 0, 0, 0}
#define MotorScopeMsg_init_zero                  {0, {{NULL}, NULL}}
#define MotorReportContainerMsg_init_zero        {0, {MotorStatusMsg_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define MotorControlMsg_speed_tag                1
#define MotorScopeMsg_period_tag                 1
#define MotorScopeMsg_values_tag                 2
#define MotorStatusMsg_speed_tag                 1
#define MotorStatusMsg_phase_current_tag         2
#define MotorStatusMsg_voltage_tag               3
#define MotorStatusMsg_pwm_magnitude_tag         4
#define MotorStatusMsg_temperature_tag           5
#define MotorReportContainerMsg_status_tag       1
#define MotorReportContainerMsg_scope_phase_current_tag 2

/* Struct field encoding specification for nanopb */
extern const pb_field_t MotorControlMsg_fields[2];
extern const pb_field_t MotorStatusMsg_fields[6];
extern const pb_field_t MotorScopeMsg_fields[3];
extern const pb_field_t MotorReportContainerMsg_fields[3];

/* Maximum encoded size of messages (where known) */
#define MotorControlMsg_size                     6
#define MotorStatusMsg_size                      25
/* MotorScopeMsg_size depends on runtime parameters */
#define MotorReportContainerMsg_size             (0 + (MotorScopeMsg_size > 27 ? MotorScopeMsg_size : 27))

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define MOTOR_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
