/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9.1 at Sat Oct  6 17:20:43 2018. */

#include "motor.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t MotorControlMsg_fields[2] = {
    PB_FIELD(  1, SINT32  , REQUIRED, STATIC  , FIRST, MotorControlMsg, speed, speed, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorStatusMsg_fields[6] = {
    PB_FIELD(  1, FLOAT   , REQUIRED, STATIC  , FIRST, MotorStatusMsg, speed, speed, 0),
    PB_FIELD(  2, FLOAT   , REQUIRED, STATIC  , OTHER, MotorStatusMsg, phase_current, speed, 0),
    PB_FIELD(  3, FLOAT   , REQUIRED, STATIC  , OTHER, MotorStatusMsg, voltage, phase_current, 0),
    PB_FIELD(  4, FLOAT   , REQUIRED, STATIC  , OTHER, MotorStatusMsg, pwm_magnitude, voltage, 0),
    PB_FIELD(  5, FLOAT   , REQUIRED, STATIC  , OTHER, MotorStatusMsg, temperature, pwm_magnitude, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorScopeMsg_fields[3] = {
    PB_FIELD(  1, UINT32  , REQUIRED, STATIC  , FIRST, MotorScopeMsg, period, period, 0),
    PB_FIELD(  2, SINT32  , REPEATED, CALLBACK, OTHER, MotorScopeMsg, values, period, 0),
    PB_LAST_FIELD
};

const pb_field_t MotorReportContainerMsg_fields[3] = {
    PB_ONEOF_FIELD(payload,   1, MESSAGE , ONEOF, STATIC  , FIRST, MotorReportContainerMsg, status, status, &MotorStatusMsg_fields),
    PB_ONEOF_FIELD(payload,   2, MESSAGE , ONEOF, STATIC  , UNION, MotorReportContainerMsg, scope_phase_current, scope_phase_current, &MotorScopeMsg_fields),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MotorReportContainerMsg, payload.status) < 65536 && pb_membersize(MotorReportContainerMsg, payload.scope_phase_current) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_MotorControlMsg_MotorStatusMsg_MotorScopeMsg_MotorReportContainerMsg)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(MotorReportContainerMsg, payload.status) < 256 && pb_membersize(MotorReportContainerMsg, payload.scope_phase_current) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_MotorControlMsg_MotorStatusMsg_MotorScopeMsg_MotorReportContainerMsg)
#endif


/* @@protoc_insertion_point(eof) */
