# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: motor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='motor.proto',
  package='',
  serialized_pb=_b('\n\x0bmotor.proto\" \n\x0fMotorControlMsg\x12\r\n\x05speed\x18\x01 \x02(\x11\"s\n\x0eMotorStatusMsg\x12\r\n\x05speed\x18\x01 \x02(\x02\x12\x15\n\rphase_current\x18\x02 \x02(\x02\x12\x0f\n\x07voltage\x18\x03 \x02(\x02\x12\x15\n\rpwm_magnitude\x18\x04 \x02(\x02\x12\x13\n\x0btemperature\x18\x05 \x02(\x02\"3\n\rMotorScopeMsg\x12\x0e\n\x06period\x18\x01 \x02(\r\x12\x12\n\x06values\x18\x02 \x03(\x11\x42\x02\x10\x01\"v\n\x17MotorReportContainerMsg\x12!\n\x06status\x18\x01 \x01(\x0b\x32\x0f.MotorStatusMsgH\x00\x12-\n\x13scope_phase_current\x18\x02 \x01(\x0b\x32\x0e.MotorScopeMsgH\x00\x42\t\n\x07payload')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MOTORCONTROLMSG = _descriptor.Descriptor(
  name='MotorControlMsg',
  full_name='MotorControlMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='MotorControlMsg.speed', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=47,
)


_MOTORSTATUSMSG = _descriptor.Descriptor(
  name='MotorStatusMsg',
  full_name='MotorStatusMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='MotorStatusMsg.speed', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='phase_current', full_name='MotorStatusMsg.phase_current', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='MotorStatusMsg.voltage', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pwm_magnitude', full_name='MotorStatusMsg.pwm_magnitude', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='MotorStatusMsg.temperature', index=4,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=164,
)


_MOTORSCOPEMSG = _descriptor.Descriptor(
  name='MotorScopeMsg',
  full_name='MotorScopeMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='period', full_name='MotorScopeMsg.period', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='values', full_name='MotorScopeMsg.values', index=1,
      number=2, type=17, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=217,
)


_MOTORREPORTCONTAINERMSG = _descriptor.Descriptor(
  name='MotorReportContainerMsg',
  full_name='MotorReportContainerMsg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='MotorReportContainerMsg.status', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scope_phase_current', full_name='MotorReportContainerMsg.scope_phase_current', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='payload', full_name='MotorReportContainerMsg.payload',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=219,
  serialized_end=337,
)

_MOTORREPORTCONTAINERMSG.fields_by_name['status'].message_type = _MOTORSTATUSMSG
_MOTORREPORTCONTAINERMSG.fields_by_name['scope_phase_current'].message_type = _MOTORSCOPEMSG
_MOTORREPORTCONTAINERMSG.oneofs_by_name['payload'].fields.append(
  _MOTORREPORTCONTAINERMSG.fields_by_name['status'])
_MOTORREPORTCONTAINERMSG.fields_by_name['status'].containing_oneof = _MOTORREPORTCONTAINERMSG.oneofs_by_name['payload']
_MOTORREPORTCONTAINERMSG.oneofs_by_name['payload'].fields.append(
  _MOTORREPORTCONTAINERMSG.fields_by_name['scope_phase_current'])
_MOTORREPORTCONTAINERMSG.fields_by_name['scope_phase_current'].containing_oneof = _MOTORREPORTCONTAINERMSG.oneofs_by_name['payload']
DESCRIPTOR.message_types_by_name['MotorControlMsg'] = _MOTORCONTROLMSG
DESCRIPTOR.message_types_by_name['MotorStatusMsg'] = _MOTORSTATUSMSG
DESCRIPTOR.message_types_by_name['MotorScopeMsg'] = _MOTORSCOPEMSG
DESCRIPTOR.message_types_by_name['MotorReportContainerMsg'] = _MOTORREPORTCONTAINERMSG

MotorControlMsg = _reflection.GeneratedProtocolMessageType('MotorControlMsg', (_message.Message,), dict(
  DESCRIPTOR = _MOTORCONTROLMSG,
  __module__ = 'motor_pb2'
  # @@protoc_insertion_point(class_scope:MotorControlMsg)
  ))
_sym_db.RegisterMessage(MotorControlMsg)

MotorStatusMsg = _reflection.GeneratedProtocolMessageType('MotorStatusMsg', (_message.Message,), dict(
  DESCRIPTOR = _MOTORSTATUSMSG,
  __module__ = 'motor_pb2'
  # @@protoc_insertion_point(class_scope:MotorStatusMsg)
  ))
_sym_db.RegisterMessage(MotorStatusMsg)

MotorScopeMsg = _reflection.GeneratedProtocolMessageType('MotorScopeMsg', (_message.Message,), dict(
  DESCRIPTOR = _MOTORSCOPEMSG,
  __module__ = 'motor_pb2'
  # @@protoc_insertion_point(class_scope:MotorScopeMsg)
  ))
_sym_db.RegisterMessage(MotorScopeMsg)

MotorReportContainerMsg = _reflection.GeneratedProtocolMessageType('MotorReportContainerMsg', (_message.Message,), dict(
  DESCRIPTOR = _MOTORREPORTCONTAINERMSG,
  __module__ = 'motor_pb2'
  # @@protoc_insertion_point(class_scope:MotorReportContainerMsg)
  ))
_sym_db.RegisterMessage(MotorReportContainerMsg)


_MOTORSCOPEMSG.fields_by_name['values'].has_options = True
_MOTORSCOPEMSG.fields_by_name['values']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
